// Uganda National Drug Library
// ------------------------------
// An ever-growing catalogue of medicines commonly stocked and officially
// recognised in Uganda (intended to mirror National Drug Authority / Ministry
// of Health lists). Used on first-time setup so the owner can *select* common
// drugs instead of typing them, and to prefill sensible pack compositions.
//
// Each entry:
//   name           — display / product name (brand-generic friendly)
//   genericName    — active pharmaceutical ingredient
//   category       — therapeutic class (for search filtering)
//   forms          — pack forms this drug is stocked in
//   defaultUnit    — the unit the shop usually buys in (Strip of 10 / Bottle / Box)
//   pack           — { stripsPerBox, tabletsPerStrip } when relevant
//   commonPrices   — rough typical retail prices in UGX (edited by owner at setup)
//
// NOTE: prices are indicative ranges, ALWAYS verified by the owner at setup.

export const MEDICINE_CATEGORIES = [
  "Analgesic / Pain relief",
  "Antibiotic",
  "Antimalarial",
  "Antipyretic / Cold & Flu",
  "Antacid / GI",
  "Antihistamine / Allergy",
  "Antifungal",
  "Anthelmintic / Dewormer",
  "Antiseptic / Skin care",
  "Vitamins / Supplements",
  "Cough & Respiratory",
  "Hydration / Electrolytes",
  "Maternity / Women's health",
  "Diabetic care",
  "Blood pressure / Heart",
  "First aid / Medical supplies",
];

export const UG_MEDICINES = [
  {
    name: "Paracetamol 500mg",
    genericName: "Paracetamol",
    category: "Analgesic / Pain relief",
    forms: ["Tablet", "Strip of 10", "Box"],
    defaultUnit: "Strip of 10",
    pack: { stripsPerBox: 10, tabletsPerStrip: 10 },
    commonPrices: { tabletPrice: 100, stripPrice: 1000, boxPrice: 4800, costPrice: 500 },
  },
  {
    name: "Paracetamol Syrup (100ml)",
    genericName: "Paracetamol",
    category: "Antipyretic / Cold & Flu",
    forms: ["Bottle"],
    defaultUnit: "Bottle",
    pack: { stripsPerBox: null, tabletsPerStrip: null },
    commonPrices: { tabletPrice: null, stripPrice: null, boxPrice: null, costPrice: 2500 },
  },
  {
    name: "Ibuprofen 400mg",
    genericName: "Ibuprofen",
    category: "Analgesic / Pain relief",
    forms: ["Tablet", "Strip of 10", "Box"],
    defaultUnit: "Strip of 10",
    pack: { stripsPerBox: 10, tabletsPerStrip: 10 },
    commonPrices: { tabletPrice: 150, stripPrice: 1500, boxPrice: 7200, costPrice: 800 },
  },
  {
    name: "Diclofenac 50mg",
    genericName: "Diclofenac",
    category: "Analgesic / Pain relief",
    forms: ["Tablet", "Strip of 10", "Box"],
    defaultUnit: "Strip of 10",
    pack: { stripsPerBox: 10, tabletsPerStrip: 10 },
    commonPrices: { tabletPrice: 200, stripPrice: 2000, boxPrice: 9000, costPrice: 1000 },
  },
  {
    name: "Amoxicillin 250mg",
    genericName: "Amoxicillin",
    category: "Antibiotic",
    forms: ["Tablet", "Strip of 10", "Box"],
    defaultUnit: "Strip of 10",
    pack: { stripsPerBox: 10, tabletsPerStrip: 10 },
    commonPrices: { tabletPrice: 300, stripPrice: 3000, boxPrice: 15000, costPrice: 1500 },
  },
  {
    name: "Amoxicillin 500mg",
    genericName: "Amoxicillin",
    category: "Antibiotic",
    forms: ["Tablet", "Strip of 10", "Box"],
    defaultUnit: "Strip of 10",
    pack: { stripsPerBox: 10, tabletsPerStrip: 10 },
    commonPrices: { tabletPrice: 400, stripPrice: 4000, boxPrice: 22000, costPrice: 2500 },
  },
  {
    name: "Ciprofloxacin 500mg",
    genericName: "Ciprofloxacin",
    category: "Antibiotic",
    forms: ["Tablet", "Strip of 6", "Box"],
    defaultUnit: "Strip of 6",
    pack: { stripsPerBox: 10, tabletsPerStrip: 6 },
    commonPrices: { tabletPrice: 500, stripPrice: 3000, boxPrice: 16000, costPrice: 2000 },
  },
  {
    name: "Metronidazole 400mg",
    genericName: "Metronidazole",
    category: "Antibiotic",
    forms: ["Tablet", "Strip of 10", "Box"],
    defaultUnit: "Strip of 10",
    pack: { stripsPerBox: 20, tabletsPerStrip: 10 },
    commonPrices: { tabletPrice: 160, stripPrice: 1600, boxPrice: 7800, costPrice: 800 },
  },
  {
    name: "Cotrimoxazole 480mg",
    genericName: "Sulfamethoxazole/Trimethoprim",
    category: "Antibiotic",
    forms: ["Tablet", "Strip of 10", "Box"],
    defaultUnit: "Strip of 10",
    pack: { stripsPerBox: 10, tabletsPerStrip: 10 },
    commonPrices: { tabletPrice: 200, stripPrice: 2000, boxPrice: 9600, costPrice: 1000 },
  },
  {
    name: "Erythromycin 250mg",
    genericName: "Erythromycin",
    category: "Antibiotic",
    forms: ["Tablet", "Strip of 6", "Box"],
    defaultUnit: "Strip of 6",
    pack: { stripsPerBox: 10, tabletsPerStrip: 6 },
    commonPrices: { tabletPrice: 300, stripPrice: 1800, boxPrice: 9000, costPrice: 1200 },
  },
  {
    name: "Azithromycin 500mg",
    genericName: "Azithromycin",
    category: "Antibiotic",
    forms: ["Tablet", "Strip of 3", "Box"],
    defaultUnit: "Strip of 3",
    pack: { stripsPerBox: 10, tabletsPerStrip: 3 },
    commonPrices: { tabletPrice: 1000, stripPrice: 3000, boxPrice: 15000, costPrice: 2200 },
  },
  {
    name: "Artemether/Lumefantrine 20/120 (Coartem)",
    genericName: "Artemether/Lumefantrine",
    category: "Antimalarial",
    forms: ["Tablet", "Strip of 6", "Strip of 12", "Box"],
    defaultUnit: "Strip of 6",
    pack: { stripsPerBox: 10, tabletsPerStrip: 6 },
    commonPrices: { tabletPrice: 1000, stripPrice: 6000, boxPrice: 28000, costPrice: 4000 },
  },
  {
    name: "Quinine 300mg",
    genericName: "Quinine",
    category: "Antimalarial",
    forms: ["Tablet", "Strip of 10", "Box"],
    defaultUnit: "Strip of 10",
    pack: { stripsPerBox: 10, tabletsPerStrip: 10 },
    commonPrices: { tabletPrice: 200, stripPrice: 2000, boxPrice: 10000, costPrice: 1300 },
  },
  {
    name: "Dihydroartemisinin/Piperaquine 40/320",
    genericName: "DHA/Piperaquine",
    category: "Antimalarial",
    forms: ["Tablet", "Strip of 6", "Box"],
    defaultUnit: "Strip of 6",
    pack: { stripsPerBox: 10, tabletsPerStrip: 6 },
    commonPrices: { tabletPrice: 900, stripPrice: 5400, boxPrice: 26000, costPrice: 3800 },
  },
  {
    name: "AL (Coartem) Junior 20/120",
    genericName: "Artemether/Lumefantrine",
    category: "Antimalarial",
    forms: ["Tablet", "Strip of 6", "Box"],
    defaultUnit: "Strip of 6",
    pack: { stripsPerBox: 10, tabletsPerStrip: 6 },
    commonPrices: { tabletPrice: 800, stripPrice: 4800, boxPrice: 23000, costPrice: 3200 },
  },
  {
    name: "ORS Sachet (20.5g)",
    genericName: "Oral Rehydration Salts",
    category: "Hydration / Electrolytes",
    forms: ["Sachet", "Box"],
    defaultUnit: "Sachet",
    pack: { stripsPerBox: null, tabletsPerStrip: null },
    commonPrices: { tabletPrice: null, stripPrice: null, boxPrice: null, costPrice: 1200 },
  },
  {
    name: "Zinc Sulfate 20mg",
    genericName: "Zinc Sulfate",
    category: "Hydration / Electrolytes",
    forms: ["Tablet", "Strip of 10", "Box"],
    defaultUnit: "Strip of 10",
    pack: { stripsPerBox: 10, tabletsPerStrip: 10 },
    commonPrices: { tabletPrice: 150, stripPrice: 1500, boxPrice: 7000, costPrice: 900 },
  },
  {
    name: "Oral Rehydration Salts (loose)",
    genericName: "ORS",
    category: "Hydration / Electrolytes",
    forms: ["Sachet"],
    defaultUnit: "Sachet",
    pack: { stripsPerBox: null, tabletsPerStrip: null },
    commonPrices: { tabletPrice: null, stripPrice: null, boxPrice: null, costPrice: 1500 },
  },
  {
    name: "Cetirizine 10mg",
    genericName: "Cetirizine",
    category: "Antihistamine / Allergy",
    forms: ["Tablet", "Strip of 10", "Box"],
    defaultUnit: "Strip of 10",
    pack: { stripsPerBox: 10, tabletsPerStrip: 10 },
    commonPrices: { tabletPrice: 200, stripPrice: 2000, boxPrice: 9000, costPrice: 800 },
  },
  {
    name: "Chlorpheniramine 4mg",
    genericName: "Chlorpheniramine",
    category: "Antihistamine / Allergy",
    forms: ["Tablet", "Strip of 10", "Box"],
    defaultUnit: "Strip of 10",
    pack: { stripsPerBox: 10, tabletsPerStrip: 10 },
    commonPrices: { tabletPrice: 100, stripPrice: 1000, boxPrice: 4800, costPrice: 500 },
  },
  {
    name: "Loratadine 10mg",
    genericName: "Loratadine",
    category: "Antihistamine / Allergy",
    forms: ["Tablet", "Strip of 10", "Box"],
    defaultUnit: "Strip of 10",
    pack: { stripsPerBox: 10, tabletsPerStrip: 10 },
    commonPrices: { tabletPrice: 250, stripPrice: 2500, boxPrice: 11000, costPrice: 1200 },
  },
  {
    name: "Salbutamol Inhaler 100mcg",
    genericName: "Salbutamol",
    category: "Cough & Respiratory",
    forms: ["Bottle"],
    defaultUnit: "Bottle",
    pack: { stripsPerBox: null, tabletsPerStrip: null },
    commonPrices: { tabletPrice: null, stripPrice: null, boxPrice: null, costPrice: 8000 },
  },
  {
    name: "Dextromethorphan Syrup (100ml)",
    genericName: "Dextromethorphan",
    category: "Cough & Respiratory",
    forms: ["Bottle"],
    defaultUnit: "Bottle",
    pack: { stripsPerBox: null, tabletsPerStrip: null },
    commonPrices: { tabletPrice: null, stripPrice: null, boxPrice: null, costPrice: 3000 },
  },
  {
    name: "Ambroxol Syrup (100ml)",
    genericName: "Ambroxol",
    category: "Cough & Respiratory",
    forms: ["Bottle"],
    defaultUnit: "Bottle",
    pack: { stripsPerBox: null, tabletsPerStrip: null },
    commonPrices: { tabletPrice: null, stripPrice: null, boxPrice: null, costPrice: 2800 },
  },
  {
    name: "Omeprazole 20mg",
    genericName: "Omeprazole",
    category: "Antacid / GI",
    forms: ["Tablet", "Strip of 10", "Box"],
    defaultUnit: "Strip of 10",
    pack: { stripsPerBox: 10, tabletsPerStrip: 10 },
    commonPrices: { tabletPrice: 250, stripPrice: 2500, boxPrice: 12000, costPrice: 1400 },
  },
  {
    name: "Ranitidine 150mg",
    genericName: "Ranitidine",
    category: "Antacid / GI",
    forms: ["Tablet", "Strip of 10", "Box"],
    defaultUnit: "Strip of 10",
    pack: { stripsPerBox: 10, tabletsPerStrip: 10 },
    commonPrices: { tabletPrice: 150, stripPrice: 1500, boxPrice: 7000, costPrice: 800 },
  },
  {
    name: "Hyoscine Butylbromide 10mg (Buscopan)",
    genericName: "Hyoscine Butylbromide",
    category: "Antacid / GI",
    forms: ["Tablet", "Strip of 10", "Box"],
    defaultUnit: "Strip of 10",
    pack: { stripsPerBox: 10, tabletsPerStrip: 10 },
    commonPrices: { tabletPrice: 300, stripPrice: 3000, boxPrice: 14000, costPrice: 1700 },
  },
  {
    name: "Metoclopramide 10mg",
    genericName: "Metoclopramide",
    category: "Antacid / GI",
    forms: ["Tablet", "Strip of 10", "Box"],
    defaultUnit: "Strip of 10",
    pack: { stripsPerBox: 10, tabletsPerStrip: 10 },
    commonPrices: { tabletPrice: 200, stripPrice: 2000, boxPrice: 9000, costPrice: 1000 },
  },
  {
    name: "Albendazole 400mg",
    genericName: "Albendazole",
    category: "Anthelmintic / Dewormer",
    forms: ["Tablet", "Strip of 10", "Box"],
    defaultUnit: "Strip of 10",
    pack: { stripsPerBox: 10, tabletsPerStrip: 10 },
    commonPrices: { tabletPrice: 300, stripPrice: 3000, boxPrice: 13000, costPrice: 1500 },
  },
  {
    name: "Mebendazole 100mg",
    genericName: "Mebendazole",
    category: "Anthelmintic / Dewormer",
    forms: ["Tablet", "Strip of 10", "Box"],
    defaultUnit: "Strip of 10",
    pack: { stripsPerBox: 10, tabletsPerStrip: 10 },
    commonPrices: { tabletPrice: 200, stripPrice: 2000, boxPrice: 9000, costPrice: 1000 },
  },
  {
    name: "Acyclovir 200mg",
    genericName: "Aciclovir",
    category: "Antiviral",
    forms: ["Tablet", "Strip of 10", "Box"],
    defaultUnit: "Strip of 10",
    pack: { stripsPerBox: 10, tabletsPerStrip: 10 },
    commonPrices: { tabletPrice: 400, stripPrice: 4000, boxPrice: 19000, costPrice: 2200 },
  },
  {
    name: "Fluconazole 150mg",
    genericName: "Fluconazole",
    category: "Antifungal",
    forms: ["Tablet", "Strip of 1", "Box"],
    defaultUnit: "Strip of 1",
    pack: { stripsPerBox: 10, tabletsPerStrip: 1 },
    commonPrices: { tabletPrice: 500, stripPrice: 500, boxPrice: 2400, costPrice: 1500 },
  },
  {
    name: "Ketoconazole 2% Cream (20g)",
    genericName: "Ketoconazole",
    category: "Antifungal",
    forms: ["Tube"],
    defaultUnit: "Tube",
    pack: { stripsPerBox: null, tabletsPerStrip: null },
    commonPrices: { tabletPrice: null, stripPrice: null, boxPrice: null, costPrice: 5000 },
  },
  {
    name: "Hydrocortisone 1% Cream (20g)",
    genericName: "Hydrocortisone",
    category: "Antiseptic / Skin care",
    forms: ["Tube"],
    defaultUnit: "Tube",
    pack: { stripsPerBox: null, tabletsPerStrip: null },
    commonPrices: { tabletPrice: null, stripPrice: null, boxPrice: null, costPrice: 3500 },
  },
  {
    name: "Gentian Violet Paint",
    genericName: "Methylrosanilinium",
    category: "Antiseptic / Skin care",
    forms: ["Bottle"],
    defaultUnit: "Bottle",
    pack: { stripsPerBox: null, tabletsPerStrip: null },
    commonPrices: { tabletPrice: null, stripPrice: null, boxPrice: null, costPrice: 2500 },
  },
  {
    name: "Betadine / Povidone Iodine 10%",
    genericName: "Povidone Iodine",
    category: "Antiseptic / Skin care",
    forms: ["Bottle"],
    defaultUnit: "Bottle",
    pack: { stripsPerBox: null, tabletsPerStrip: null },
    commonPrices: { tabletPrice: null, stripPrice: null, boxPrice: null, costPrice: 6000 },
  },
  {
    name: "Diclofenac Gel 1% (30g)",
    genericName: "Diclofenac",
    category: "Analgesic / Pain relief",
    forms: ["Tube"],
    defaultUnit: "Tube",
    pack: { stripsPerBox: null, tabletsPerStrip: null },
    commonPrices: { tabletPrice: null, stripPrice: null, boxPrice: null, costPrice: 5000 },
  },
  {
    name: "ORS + Zinc Combo Pack",
    genericName: "ORS + Zinc",
    category: "Hydration / Electrolytes",
    forms: ["Box"],
    defaultUnit: "Box",
    pack: { stripsPerBox: 10, tabletsPerStrip: 10 },
    commonPrices: { tabletPrice: null, stripPrice: null, boxPrice: 15000, costPrice: 10000 },
  },
  {
    name: "Vitamin C 1000mg",
    genericName: "Ascorbic Acid",
    category: "Vitamins / Supplements",
    forms: ["Tablet", "Strip of 10", "Box"],
    defaultUnit: "Strip of 10",
    pack: { stripsPerBox: 10, tabletsPerStrip: 10 },
    commonPrices: { tabletPrice: 200, stripPrice: 2000, boxPrice: 9000, costPrice: 1000 },
  },
  {
    name: "Multivitamin Tablets",
    genericName: "Multivitamins",
    category: "Vitamins / Supplements",
    forms: ["Tablet", "Strip of 10", "Bottle"],
    defaultUnit: "Strip of 10",
    pack: { stripsPerBox: 10, tabletsPerStrip: 10 },
    commonPrices: { tabletPrice: 150, stripPrice: 1500, boxPrice: 7000, costPrice: 900 },
  },
  {
    name: "Folic Acid 5mg",
    genericName: "Folic Acid",
    category: "Maternity / Women's health",
    forms: ["Tablet", "Strip of 10", "Box"],
    defaultUnit: "Strip of 10",
    pack: { stripsPerBox: 10, tabletsPerStrip: 10 },
    commonPrices: { tabletPrice: 100, stripPrice: 1000, boxPrice: 4800, costPrice: 500 },
  },
  {
    name: "Ferrous Sulphate + Folic Acid",
    genericName: "Iron + Folic Acid",
    category: "Maternity / Women's health",
    forms: ["Tablet", "Strip of 10", "Box"],
    defaultUnit: "Strip of 10",
    pack: { stripsPerBox: 10, tabletsPerStrip: 10 },
    commonPrices: { tabletPrice: 200, stripPrice: 2000, boxPrice: 9000, costPrice: 1000 },
  },
  {
    name: "Metformin 500mg",
    genericName: "Metformin",
    category: "Diabetic care",
    forms: ["Tablet", "Strip of 10", "Box"],
    defaultUnit: "Strip of 10",
    pack: { stripsPerBox: 10, tabletsPerStrip: 10 },
    commonPrices: { tabletPrice: 200, stripPrice: 2000, boxPrice: 9000, costPrice: 1100 },
  },
  {
    name: "Glibenclamide 5mg",
    genericName: "Glibenclamide",
    category: "Diabetic care",
    forms: ["Tablet", "Strip of 10", "Box"],
    defaultUnit: "Strip of 10",
    pack: { stripsPerBox: 10, tabletsPerStrip: 10 },
    commonPrices: { tabletPrice: 150, stripPrice: 1500, boxPrice: 7000, costPrice: 800 },
  },
  {
    name: "Amlodipine 5mg",
    genericName: "Amlodipine",
    category: "Blood pressure / Heart",
    forms: ["Tablet", "Strip of 10", "Box"],
    defaultUnit: "Strip of 10",
    pack: { stripsPerBox: 10, tabletsPerStrip: 10 },
    commonPrices: { tabletPrice: 250, stripPrice: 2500, boxPrice: 12000, costPrice: 1300 },
  },
  {
    name: "Nifedipine 20mg",
    genericName: "Nifedipine",
    category: "Blood pressure / Heart",
    forms: ["Tablet", "Strip of 10", "Box"],
    defaultUnit: "Strip of 10",
    pack: { stripsPerBox: 10, tabletsPerStrip: 10 },
    commonPrices: { tabletPrice: 200, stripPrice: 2000, boxPrice: 9000, costPrice: 1100 },
  },
  {
    name: "Aspirin 75mg (Cardio)",
    genericName: "Acetylsalicylic Acid",
    category: "Blood pressure / Heart",
    forms: ["Tablet", "Strip of 10", "Box"],
    defaultUnit: "Strip of 10",
    pack: { stripsPerBox: 10, tabletsPerStrip: 10 },
    commonPrices: { tabletPrice: 100, stripPrice: 1000, boxPrice: 4500, costPrice: 500 },
  },
  {
    name: "Diazepam 5mg",
    genericName: "Diazepam",
    category: "Nervous system",
    forms: ["Tablet", "Strip of 10", "Box"],
    defaultUnit: "Strip of 10",
    pack: { stripsPerBox: 10, tabletsPerStrip: 10 },
    commonPrices: { tabletPrice: 300, stripPrice: 3000, boxPrice: 14000, costPrice: 1600 },
  },
  {
    name: "Surgical Gloves (Pair)",
    genericName: "Medical Supplies",
    category: "First aid / Medical supplies",
    forms: ["Box"],
    defaultUnit: "Box",
    pack: { stripsPerBox: null, tabletsPerStrip: null },
    commonPrices: { tabletPrice: null, stripPrice: null, boxPrice: null, costPrice: 2000 },
  },
  {
    name: "Cotton Wool (25g)",
    genericName: "Medical Supplies",
    category: "First aid / Medical supplies",
    forms: ["Box"],
    defaultUnit: "Box",
    pack: { stripsPerBox: null, tabletsPerStrip: null },
    commonPrices: { tabletPrice: null, stripPrice: null, boxPrice: null, costPrice: 3000 },
  },
  {
    name: "Adhesive Bandages / Plasters",
    genericName: "Medical Supplies",
    category: "First aid / Medical supplies",
    forms: ["Box"],
    defaultUnit: "Box",
    pack: { stripsPerBox: null, tabletsPerStrip: null },
    commonPrices: { tabletPrice: null, stripPrice: null, boxPrice: null, costPrice: 2000 },
  },
  {
    name: "Gauze Swabs",
    genericName: "Medical Supplies",
    category: "First aid / Medical supplies",
    forms: ["Box"],
    defaultUnit: "Box",
    pack: { stripsPerBox: null, tabletsPerStrip: null },
    commonPrices: { tabletPrice: null, stripPrice: null, boxPrice: null, costPrice: 2500 },
  },
  {
    name: "Cough Syrup (100ml)",
    genericName: "Cough Syrup",
    category: "Cough & Respiratory",
    forms: ["Bottle"],
    defaultUnit: "Bottle",
    pack: { stripsPerBox: null, tabletsPerStrip: null },
    commonPrices: { tabletPrice: null, stripPrice: null, boxPrice: null, costPrice: 2000 },
  },
];

// Search helper used by the setup/library picker
export function searchMedicines(query = "") {
  const q = query.trim().toLowerCase();
  if (!q) return UG_MEDICINES;
  return UG_MEDICINES.filter(
    (m) =>
      m.name.toLowerCase().includes(q) ||
      m.genericName.toLowerCase().includes(q) ||
      m.category.toLowerCase().includes(q)
  );
}